/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javalambda;


import com.amazonaws.services.lambda.runtime.Context;
import com.amazonaws.services.lambda.runtime.LambdaLogger;
import javalambda.Model.Pokemon;
import javalambda.Model.request.LexRequest;
import javalambda.Model.response.DialogAction;
import javalambda.Model.response.LexResponse;
import javalambda.Model.response.Message;
import java.io.*;
import java.net.HttpURLConnection;
import java.net.URL;
import java.util.Map;
import com.google.gson.Gson;

public class App {
    /**
     *
     * @param lexRequest
     * @param context
     * @return
     */
    public LexResponse myHandler(LexRequest lexRequest, Context context) {
        // Grab slots i.e user inputs from lex request obj
        Map<String, String> slots = lexRequest.getCurrentIntent().getSlots();
        String inputPokemon = "";
        String inputPokemonFact = "";
        Message message = new Message();

        // Itereate thru slots to grab user inputs
        for(Map.Entry<String, String> slot : slots.entrySet()){
            if(slot.getKey().contains("Pokemon")){
                inputPokemon = slot.getValue();
            }
            if(slot.getKey().contains("PokemonFact")){
                inputPokemonFact = slot.getValue();
            }
        }

        // http request
        Gson gson = new Gson();
        try {
            URL url = new URL("http://pokeapi.co/api/v2/pokemon/"+inputPokemon+"/");
            HttpURLConnection con = (HttpURLConnection) url.openConnection();
            BufferedReader reader = new BufferedReader(new InputStreamReader((con.getInputStream())));
            Pokemon pokemon = gson.fromJson(reader, Pokemon.class);
            message.setContentType("PlainText");
            message.setContent(String.valueOf(pokemon.getOrder()));
        } catch(IOException ex) {
            System.out.println("An error occurred");
        }

        System.out.println("message" + message.getContent());

        // Build out response object: Message --> DialogAction --> LexResponse
        DialogAction dialogAction = new DialogAction("Close", "Fulfilled", message);

        LexResponse lex = new LexResponse(dialogAction);
        LambdaLogger logger = context.getLogger();
        logger.log("Pokemon Facts: " + lex.getDialogAction().getMessage().getContent());
        return lex;
    }
}

